# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # Changed from Role
metadata:
  name: custom-scheduler-clusterrole
rules:
- apiGroups: [""] # Core API group
  resources: ["pods/binding"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler-clusterbinding
subjects:
- kind: ServiceAccount
  name: custom-scheduler
  namespace: default # Note: you will need to change this manually if you want to run in another namespace
roleRef:
  kind: ClusterRole
  name: custom-scheduler-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
