
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      containers:
      - name: custom-scheduler
        image: docker.io/custom-scheduler:latest
        imagePullPolicy: Never
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SCHEDULER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      serviceAccountName: custom-scheduler
