apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      containers:
      - name: custom-scheduler
        image: docker.io/custom-scheduler:latest
        imagePullPolicy: Never
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SCHEDULER_NAME
            # Harcode this since it will likely end up hardcooded
            # when used in downstream `schedulerName` references
            value: custom-scheduler
      # If the scheduler doesn't do anything in a multinode setup, it is possible uncommenting the
      # two lines below will help.
      # nodeSelector:
      #   node-role.kubernetes.io/control-plane: ""
      serviceAccountName: custom-scheduler
